jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'

    handlers:
        datetime:
            default_format: "Y-m-d\\TH:i:s" # As the system does not care about timezones (yet?!), we do not want them

    default_context:
        serialization:
            serialize_null: true

#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
