twig:
    paths:
        '%kernel.project_dir%/templates': ~
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
        - "form.html.twig"
    globals:
        config: '@SchulIT\CommonBundle\Twig\ConfigVariable'
        user: '@App\Twig\UserVariable'
        settings: '@App\Twig\SettingsVariable'
        profile_url: "%env(IDP_PROFILE_URL)%"